# Generated by Django 5.1.5 on 2025-02-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('education', models.CharField(blank=True, choices=[('High School Diploma', 'High School Diploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctoral Degree', 'Doctoral Degree'), ('Other', 'Other')], max_length=100, null=True)),
                ('employment', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelancer', 'Freelancer'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], max_length=100, null=True)),
                ('race', models.CharField(blank=True, choices=[('South Asian', 'South Asian'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native American or Alaska Native', 'Native American or Alaska Native'), ('White', 'White'), ('Other', 'Other')], max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Germany', 'Germany'), ('France', 'France')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('less than 10', 'less than 10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('500-1000', '500-1000'), ('more than 1000', 'more than 1000')], max_length=100, null=True)),
                ('job_function', models.CharField(blank=True, choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('HR', 'HR'), ('other', 'other')], max_length=100, null=True)),
                ('job_industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Energy', 'Energy'), ('other', 'other')], max_length=100, null=True)),
                ('job_level', models.CharField(blank=True, choices=[('entry level', 'entry level'), ('mid level', 'mid level'), ('senior level', 'senior level'), ('executive', 'executive'), ('other', 'other')], max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='respondent_set', to='auth.group', verbose_name='groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='respondent_set', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
    ]
