# Generated by Django 5.1.5 on 2025-02-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondent_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='user_permissions',
        ),
    ]
