# Generated by Django 5.0 on 2025-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_survey_external_link_survey_external_response_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expiry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
