# Generated by Django 5.1.5 on 2025-02-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_expiry_datetime_survey_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='expiry_datetime',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_expired',
        ),
    ]
