# Generated by Django 5.0 on 2025-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_remove_survey_expiry_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expiry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
