# Generated by Django 5.0 on 2025-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_remove_survey_expiry_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expiry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
