# Generated by Django 5.1.5 on 2025-02-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_survey_expiry_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='expiry_datetime',
        ),
    ]
