# Generated by Django 5.1.5 on 2025-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_remove_survey_expiry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expiry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
