# Generated by Django 5.1.5 on 2025-02-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_survey_expiry_datetime_survey_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
