# Generated by Django 5.1.5 on 2025-02-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_survey_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_eligibility_flag',
            field=models.BooleanField(default=False),
        ),
    ]
