# Generated by Django 5.1.5 on 2025-02-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_surveypage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyPage',
        ),
    ]
