# Generated by Django 5.1.5 on 2025-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_surveypage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveypage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='surveypage',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='surveypage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
