# Generated by Django 5.1.5 on 2025-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_question_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveypage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surveypage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
